### ISSUE TITLE
Adding multiple edges override previous node properties

### ISSUE THREAD

**Issue by timlrx** [cylynx/motif.gl#173]
## Expected Behavior

Node properties should be shallow merged and retained

## Current Behavior

Subsequent edge import seems to override previous node properties

## Steps to Reproduce

Import node1 and edge1

node1.csv
```
id,value
a,10
b,20
c,30
```

edge1.csv
```
source,target,edge1
a,b,0
b,c,1
a,c,0
```

import edge2 are edge list
```
source,target,edge2
a,b,2
b,c,2
a,c,2
```

Examine node properties on graph and value no longer appears. Can't style based on value as well.

**Comment by CodesAreHonest** [comment]
This issue occurs during edge are grouped and its attributes are not correctly merged, the ungrouped edges work fine. Will take a look on it.

**Comment by CodesAreHonest** [comment]
Thanks for the issue and detail reproduction steps, able to reproduce the bugs on my side.
