### ISSUE TITLE
Changing node and edge options should not re-trigger layout

### ISSUE THREAD

**Issue by timlrx** [cylynx/motif.gl#174]
# Feature Request

Request from Marton

### Description

Currently, if you change  node and edge options, the layout positions gets re-applied. This is quite an irritating behaviour since most of the time you have already adjusted the positions manually. 

Layout should only change when new data is added or removed, data is filtered or layout is explicitly triggered. Otherwise, for a better user experience, it should remain as it is when other node and edge options are adjusted.

**Comment by CodesAreHonest** [comment]
## TODO 

* [ ] 1. Layout should not re-trigger when node options and edge options are applied. 
* [ ] 2. Layout should only re-trigger during data modification, layout options re-selection.
